### ISSUE TITLE
--toggle option gives segmentation fault

### ISSUE THREAD

**Issue by jakubfabijan** [fusionhuh/deskimg#2]
![bildo](https://user-images.githubusercontent.com/53099243/175721209-48bc6d07-fd64-4568-b32d-007a963a8629.png)

**Comment by fusionhuh** [comment]
hi there, could you try specifying an image file with the -f option and see if it produces the same behavior? i believe the issue may be that the program is trying to open an invalid filename with nothing specified, will fix it if that's the case

**Comment by rensenware** [comment]
I have the same issue. The program also crashes if I have the save option. This is the output I get in the terminal for a crashed program:

`~ % deskimg -s -t -f Pictures/volcarona.gif -x 1780 -y 960

(process:19455): GLib-WARNING **: 23:01:08.643: ../glib/glib/goption.c:2447: ignoring no-arg, optional-arg or filename flags (8) on option of arg-type 0 in entry (null):save

(process:19455): GLib-WARNING **: 23:01:08.644: ../glib/glib/goption.c:2447: ignoring no-arg, optional-arg or filename flags (8) on option of arg-type 0 in entry (null):toggle

(process:19455): GLib-WARNING **: 23:01:08.644: ../glib/glib/goption.c:2447: ignoring no-arg, optional-arg or filename flags (8) on option of arg-type 0 in entry (null):reset
zsh: segmentation fault (core dumped)  deskimg -s -t -f Pictures/volcarona.gif -x 1780 -y 960`

I can send you my binary if need be- I'm running on Arch Linux. The Glib-WARNING things in standard error also occur if it doesn't crash, such as if I just remove the -t and -s flags, but the program does not crash.

**Comment by fusionhuh** [comment]
hi there, to my knowledge the glib warnings are benign and appear in a number of other gtk applications, so i don't believe they're related to this issue (still looking for a way to suppress them though).

just to clarify, the gif is displayed properly when the -s and -t options are off, correct? also, is the segfault triggered by you attempting to save/toggle or just immediately on startup?

**Comment by rensenware** [comment]
Yes, the gif is displayed properly with no issues without those flags. If I try to run the program with the save flag or the toggle flag or both, it immediately crashes on startup with a segfault.

**Comment by fusionhuh** [comment]
thank you, that narrows it down quite a bit. i don't think providing the binary is necessary atm but i will let you know if i need more info

**Comment by fusionhuh** [comment]
hi i'm actually having quite a bit of trouble locating the cause of the segfault in your case. could you pull the most recent repo and make install, then upload the binary + core file? to upload the core file, you first need to run `ulimit -c unlimited', and then it should be in the same directory you ran deskimg from

**Comment by rensenware** [comment]
Sure, here's both:

https://file.io/1Rld5jQwkRas

Cloned right before I sent this message, and the only changes I've made to any files are to change the prefix in the Makefile to /home/rensenware/.local.

**Comment by fusionhuh** [comment]
hi there, i think i finally located the cause of the segfaults. i just updated the repo, let me know if the issue still persists

**Comment by rensenware** [comment]
Issue is fixed. Thanks!
