### ISSUE TITLE
XDG Specification

### ISSUE THREAD

**Issue by wael444** [fusionhuh/deskimg#3]
currently, `deskimg` puts files in the local `.deskimg` directory.

please see https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html or choose a different directoy for example `~/.local/share/deskimg` for resources and `~/.config/deskimg/config.sh` for config

**Comment by fusionhuh** [comment]
👍 will hopefully have this updated by later tonight or early tomorrow

**Comment by wael444** [comment]
just curious, what is the purpose of the `config.sh` file?

**Comment by fusionhuh** [comment]
if someone found a setup they really liked i figured it would be annoying for them to have to reposition all of the graphics every time they rebooted their computer. basically the user can double right click on the graphic and it will save the relevant details (file, position, opacity) as a command line execution (`deskimg --file # --x-pos # --y-pos # --opacity # &`) to `config.sh`, and then the user can run the script whenever they want.
