### ISSUE TITLE
Several arguments give segfaults.

### ISSUE THREAD

**Issue by epicsucks** [fusionhuh/deskimg#5]
Reset toggle and save all give segfaults for some reason. I tried with both long and short variants, and I even created ~/.config/deskimg/config.sh manually, and I get the same issue.

I also get these glib warns every time I use the program. I'm not sure if this is an actual problem or to be expected:
(process:25155): GLib-WARNING **: 22:23:20.036: ../glib/glib/goption.c:2447: ignoring no-arg, optional-arg or filename flags (8) on option of arg-type 0 in entry (null):save

(process:25155): GLib-WARNING **: 22:23:20.037: ../glib/glib/goption.c:2447: ignoring no-arg, optional-arg or filename flags (8) on option of arg-type 0 in entry (null):toggle

(process:25155): GLib-WARNING **: 22:23:20.037: ../glib/glib/goption.c:2447: ignoring no-arg, optional-arg or filename flags (8) on option of arg-type 0 in entry (null):reset

**Comment by fusionhuh** [comment]
hi there. this same problem was discussed on another issue thread and has (hopefully) been fixed. i just updated the repo, let me know if the issue still persists. the glib warnings are unrelated to the problem, and as far as i can tell they unfortunately come with a lot of gtk programs that use no-arg options. i'm currently looking for a way to suppress them.

**Comment by epicsucks** [comment]
Yep, no more segfaults. Thanks a lot for fixing it!  Although I'm curious what the save option is supposed to do, as the config file you mention in the README appears to b empty even when I have passed in the save option on a gif.

**Comment by fusionhuh** [comment]
the save option enables dynamic saving of the position of the graphic. to actually save, you need to double right click on the graphic, which will then write a deskimg call to config.sh with the -x and -y options having the positions at the time of saving.
